version: '3'

services:
  hks_mongo_db:
    image: mongo:latest
    ports:
      - "27017:27017"

  hks_hyperopt:
    build:
      context: ..
      dockerfile: local_infra/Dockerfile.cpu
    command: python /hyper_param/hyperopt_optimize.py
    depends_on:
      - hks_mongo_db
    env_file:
      - ../.env
    volumes:
      - ../results/:/hyper_param/results/

  hks_hyperopt_worker:
    build:
      context: ..
      dockerfile: local_infra/Dockerfile.gpu
    command: hyperopt-mongo-worker --mongo hks_mongo_db:27017/testing --exp-key=testing --last-job-timeout=30 --reserve-timeout=200
    depends_on:
      - hks_mongo_db
    env_file:
      - ../.env
    volumes:
      - ../results/:/hyper_param/results/
